name: Shelley Gent Music
favicon: null
layout_spectrum: 1
typography_spectrum: 0.11148
title: Shelley Gent Music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000900'
    - '#004fd7'
    - '#00ccc0'
    - '#92cb53'
    - '#409e56'
  brandStrength: 0.3690911934245378
  lightness: 0.375
  saturation: 0.6873522559180856
  rhythmicContrast: 0
purpose: []
